# Generated by Django 3.0.3 on 2020-04-04 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_fname', models.CharField(max_length=264)),
                ('user_lname', models.CharField(max_length=264)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_address', models.CharField(max_length=264)),
                ('user_contact', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User_login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=264)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodsys.New_User')),
            ],
        ),
    ]
