# Generated by Django 3.0.3 on 2020-04-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodsys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FoodItem_id', models.IntegerField(unique=True)),
                ('FoodItem_name', models.CharField(max_length=264)),
                ('FoodItem_desc', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Merchant_id', models.IntegerField(unique=True)),
                ('Merchant_name', models.CharField(max_length=264)),
                ('Merchant_contact', models.IntegerField()),
                ('Merchant_address', models.CharField(max_length=264)),
            ],
        ),
    ]
